-- local M = {}
--
--
--
-- function M.ack_visual()
--   local saved = vim.fn.getreg('"')
--   vim.cmd('normal! `<v`>y')
--   local search = vim.fn.getreg('"')
--   vim.fn.setreg('"', saved)
--   vim.cmd('silent Ack! ' .. vim.fn.shellescape(search) .. ' .')
--   vim.cmd('copen')
-- end
--
-- function M.ack_full_text_search(value, directory)
--   vim.cmd('silent Ack! ' .. vim.fn.shellescape(value) .. ' ' .. vim.fn.shellescape(directory))
--   vim.fn.matchadd('Search', value)
-- end
--
-- return M
